from .auth_controller import AuthController
from .inventario_controller import InventoryController
from .ventas_controller import VentasController
from .users_controller import UsersController
from .ventas_controller import VentasController